server:
  http_port: "8081"
  grpc_port: "9090"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

logging:
  level: "info"
  file_path: "logs"
  file_name: "db-service.log"
  format: "json"

database:
  host: "localhost"
  port: 5432
  name: "checklist"
  user: "postgres"
  password: "password"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: "300s"
  query_timeout: "30s"

redis:
  enabled: true
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  ttl: "300s"